Use posix separators for `convex.config` (#41957)
Fixes an error with separators in windows vs. unix:
```Error: ROR] Could not resolve "./convex\\convex.config.js"

  ✖ esbuild failed: Error: Build failed with 1 error:
  error: Could not resolve "./convex\\convex.config.js"
```

We have to use `\` instead of`/` sometimes in the definition path.

GitOrigin-RevId: 1457a5170c8a52784f828bffd2b82a91bbf7dd7c