Remove line returns from error messages (#27503)
This PR updates the error messages from the Fivetran destination connector so that they don’t contain line returns. We do so because the Fivetran dashboard UI doesn’t display line returns in error messages, which can be confusing for the users (e.g. when the error message contains code blocks with `//` comments).

Here’s an example of an error messages which doesn’t work well without line returns:

```
java.lang.RuntimeException: Assert table failed: The table `links` from your data source is missing in the schema of your Convex destination.Please edit your `schema.ts` file to add the table. You can use the following table definition:```import { defineSchema, defineTable } from "convex/server";import { v } from "convex/values";export default defineSchema({  // …  links: defineTable({    alias: v.union(v.string(), v.null()),    clicks: v.union(v.float64(), v.null()),    date: v.union(v.string(), v.null()),    fivetran: v.object({synced: v.float64()}),    link: v.union(v.string(), v.null()),  })    .index("by_fivetran_synced", ["fivetran.synced"])    .index("by_primary_key", ["_row"]),});```
```

GitOrigin-RevId: 49f5f72e5857a84e4a0ee6fee881b129238bb7f8